import { ThemeConfig } from '@/types/shared/Theme';

const appColors = {
  borderRadius: 6,
  colorPrimary: '#1677ff',
  typography: '#38CAB5',
  lebel_color: '#E9EAEF',
  green_color: '#47B263',
  light_green_color: '',
  title_color: '#374151',
  grey_color: '#BCC1CE',
  iconColor: '#373A3C',
  primary_color: '#38CAB5',
  light_grey_color: '#E9EAEF',
  heading_color: '#E9EAEF',
  white_color: '#FFFFFF',
  button_Border_Color: '#D1D5DB',
  default_button_color: '#6B7280',
  tab_active_color: '#4CCFBC',
  drop_down_text_color: '#4B5563',
  tab_color: '#9CA3AF',
  card_border_color: '#E5E7EB',
  Button: {
    colorPrimary: '#00B96B',
  },
};

const appFontSize = {
  font_Size_32: '32px',
  font_Size_24: '24px',
  font_Size_20: '20px',
  font_Size_18: '18px',
  font_Size_16: '16px',
  font_Size_14: '14px',
};
const appFontWeight = {
  fontWeight: 500,
  font_weight_600: 600,
  font_weight_700: 700,
};
const appLineHeight = {
  line_height_32: '32px',
  line_height_20: '20px',
  line_height_18: '18px',
  line_height_16: '16px',
  line_height_14: '14px',
  line_height_12: '12px',
};
const appBorderRadius = {
  border_radius_8: '8px',
  border_radius_12: '12px',
  border_radius_16: '16px',
  border_radius_18: '18px',
  border_radius_20: '20px',
};

export const theme: ThemeConfig = {
  components: {
    Button: {
      colorPrimary: appColors?.primary_color,
      colorPrimaryHover: appColors?.primary_color,
      // fontSize: appFontSize?.fontSize,
      fontWeight: appFontWeight?.fontWeight,
      // lineHeight: appLineHeight?.lineHeight,
      primaryColor: appColors?.white_color,
      defaultBorderColor: appColors?.button_Border_Color,
      defaultColor: appColors?.default_button_color,
    },
    Typography: {
      colorText: appColors?.title_color,
      colorError: 'green',
      fontSizeHeading1: appFontSize?.font_Size_32,
      fontSizeHeading2: appFontSize?.font_Size_24,
      fontSizeHeading3: appFontSize?.font_Size_20,
      fontSizeHeading4: appFontSize?.font_Size_18,
      fontSizeHeading5: appFontSize?.font_Size_16,
      lineHeightHeading1: appLineHeight?.line_height_20,
      lineHeightHeading2: appLineHeight?.line_height_18,
      lineHeightHeading3: appLineHeight?.line_height_16,
      lineHeightHeading4: appLineHeight?.line_height_14,
      lineHeightHeading5: appLineHeight?.line_height_12,
      fontWeightStrong: 600,
    },
    Tabs: {
      itemSelectedColor: appColors?.tab_active_color,
      itemColor: appColors?.tab_color,
      inkBarColor: appColors?.tab_active_color,
      itemHoverColor: appColors?.tab_active_color,
      // titleFontSize: appFontSize?.tab_font_size,
      lineHeight: appLineHeight?.line_height_12,
    },

    Dropdown: {
      borderRadiusLG: appBorderRadius?.border_radius_8,
      boxShadowSecondary:
        '0px 4px 6px -2px rgba(16, 24, 40, 0.03), 0px 12px 16px -4px rgba(16, 24, 40, 0.08)',
      colorText: appColors?.drop_down_text_color,
      fontSize: appFontSize?.font_Size_16,
      lineHeight: '40px',
      paddingXXS: '16px',
    },
    Card: {
      colorBorderSecondary: appColors?.card_border_color,
      borderRadiusLG: appBorderRadius?.border_radius_12,
    },
    Select: {
      borderRadius: appBorderRadius?.border_radius_8,
      colorText: appColors?.tab_color,
      colorPrimaryHover: appColors?.primary_color,
    },
    Input: {
      colorPrimaryHover: appColors?.primary_color,
      colorText: appColors?.tab_color,
      borderRadius: appBorderRadius?.border_radius_8,
      controlHeight: '100',
      lineHeight: '100',
    },
    Table: {
      borderColor: '#EAECF0',
      filterDropdownBg: 'red',
      filterDropdownMenuBg: 'red',
      fixedHeaderSortActiveBg: 'red',
      headerColor: '#1F305D',
      rowExpandedBg: '#EAECF0',
      rowHoverBg: '',
      rowSelectedHoverBg: '#FFFFFF',
      colorIcon: '#D0D5DD',
      colorIconHover: '#D0D5DD',
      colorText: '#6B7280',
    },
    Pagination: {
      colorPrimary: '',
      itemActiveBg: '#D1D5DB',
      colorText: 'black',
      paddingSM: 60,
      borderRadius: 0,
      lineType: 'solid',
      itemSize: 40,
      fontWeightStrong: appFontWeight?.font_weight_600,
      colorPrimaryHover: '',
      wireframe: false,
    },
    Switch: {
      colorPrimary: appColors?.primary_color,
      colorPrimaryBorder: appColors?.primary_color,
      colorPrimaryHover: appColors?.primary_color,
    },
    Checkbox: {
      colorPrimary: '',
      colorPrimaryHover: '',
      colorBorder: '#D1D5DB',
      colorWhite: appColors?.primary_color,
      borderRadiusSM: 4,
    },
    Drawer: {
      colorBgElevated: appColors?.white_color,
      colorIcon: '#373A3C',
      colorSplit: appColors?.white_color,
      colorText: appColors?.title_color,
      fontSizeLG: appFontSize?.font_Size_20,
      fontWeightStrong: 700,
      lineHeightLG: 2,
      // marginSM:170,
    },
    Modal: {
      contentBg: appColors?.white_color,
      footerBg: appColors?.white_color,
      headerBg: appColors?.white_color,
      titleColor: appColors?.title_color,
      colorIcon: appColors?.default_button_color,
      colorText: appColors?.drop_down_text_color,
      titleFontSize: appFontSize?.font_Size_24,
      titleLineHeight: 0.7,
      borderRadiusLG: appBorderRadius?.border_radius_20,
      fontWeightStrong: 600,
    },
  },
};
